# Generated by Django 3.2 on 2022-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='stripe_coupon_id_rub',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Stripe id скидки для rub'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='stripe_coupon_id_usd',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Stripe id скидки для usd'),
        ),
    ]
